### ISSUE TITLE
setuptools:: AttributeError: 'module' object has no attribute 'packaging'

### ISSUE THREAD

**Issue by jorjun** [pebble/homebrew-pebble-sdk#44]
Installing setuptools, pip, wheel...done.
(pebble)jorjun@horus project_pebble $python -V
Python 3.5.1
(pebble)jorjun@horus project_pebble $brew upgrade pebble-sdk
==> Upgrading 1 outdated package, with result:
pebble/pebble-sdk/pebble-sdk 4.2.1
==> Upgrading pebble/pebble-sdk/pebble-sdk
==> Downloading https://github.com/pebble/pebble-tool/archive/v4.2.1.zip
Already downloaded: /Library/Caches/Homebrew/pebble-sdk-4.2.1.zip
==> Downloading https://s3-us-west-2.amazonaws.com/pebble-sdk-homebrew/pypkjs-1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--pypkjs-1.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/pebble-sdk/4.2.1/
Last 15 lines from /Users/jorjun/Library/Logs/Homebrew/pebble-sdk/01.python:
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/pebble-sdk/4.2.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/__init__.py", line 11, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/extension.py", line 8, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/setuptools/dist.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'packaging'

**Comment by jorjun** [comment]
$brew config

HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b9552a5fbf3772b408cdb25c3a545bb1444ba8ff
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 226dc885e0822f5f1e090b355992baeff18338c8
Core tap last commit: 75 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
Clang: 7.3 build 703
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
System Ruby: 2.0.0-p648
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: N/A
X11: 2.7.8 => /opt/X11
j
